fix postgres autoIncrement seq with createIfNoExists issue #2099
slick/slick pull request #2100
Opened 2020-02-19 07:16 UTC by mdibaiee

Fixes #2099

2020-09-25 19:04 UTC, jfilali commented
Any plan to merge this? It seems pretty straightforward but will prevent users to spend enormous amounts of time trying to figure out why it doesn't work as expected.   Thank so much.

2021-03-13 17:24 UTC, SethTisue commented
if this is still relevant, rebase on current master? then we can try again to find a reviewer

2021-03-15 09:25 UTC, mdibaiee commented
Hey @SethTisue, I just rebased on master and pushed again. 👍

2021-03-16 16:05 UTC, SethTisue commented
Would anyone watching this repo like to review it?

(It looks this was already discussed pretty thoroughly on the bug, so if no new reviewer appears in the next week or two, I'd say we could merge this anyway.)

2021-04-18 04:38 UTC, nafg commented
Closing and reopening to trigger CI

2021-04-26 16:59 UTC, nafg submitted a review, later dismissed

2021-04-26 17:27 UTC, nafg commented
This works, but it seems more like a workaround rather than a proper fix. If you look all the way back to where `autoIncrement = false` was introduced, 805c05a14133d7627dbfc110bf5a1f6a52f44405, it seems like it was just a lazy shortcut to avoid overriding `appendOptions` like was done for other drivers, to just get it not to append `AUTO_INCREMENT` since `SERIAL` was specified as the type. I think `autoIncrement` should be kept as `true` and the postgres ddl should just override `appendOptions` to be the same as in basic ddl except without AUTO_INCREMENT.

2021-04-26 17:29 UTC, nafg requested changes
Can you supply a test, and try my suggestion of overriding `appendOptions` and never reassigning `autoIncrement`?

2021-05-19 02:31 UTC, nafg requested changes

2021-05-19 02:31 UTC, nafg commented on slick/src/main/scala/slick/jdbc/PostgresProfile.scala
> +      autoIncrement = originalAutoIncrement
```suggestion
```

2021-06-06 22:17 UTC, nafg commented
@mdibaiee are you planning on taking this further?

2021-06-11 12:38 UTC, mdibaiee commented
Hey @nafg, sorry for late replies. I still have not got to test this new approach. A minimal test case is available here though, I just need to run it: https://github.com/mdibaiee/slick-bug-sequences

2021-06-23 09:29 UTC, mdibaiee commented
I did a manual test with the example here and it worked! https://github.com/mdibaiee/slick-bug-sequences

I will see if I can write an automated test now 👍

2021-06-23 10:30 UTC, lightbend-cla-validator commented
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

2021-06-23 11:23 UTC, mdibaiee commented
On my local instance the test does not run for postgres apparently 🤔 
I'm not sure if I can make it run for postgres as well, or if the pipeline is enough for that?

2021-06-24 04:37 UTC, nafg approved these changes

2021-06-24 19:19 UTC, nafg commented
Failure: https://github.com/slick/slick/pull/2100/checks?check_run_id=2907117315#step:9:2039

Seems it like fails only on MySQL, with "Incorrect table definition; there can be only one auto column and it must be defined as a key."

```
[error] Test com.typesafe.slick.testkit.tests.JdbcMiscTest.testAutoIncrementCreateIfNotExists[mysql] failed: java.sql.SQLSyntaxErrorException: Incorrect table definition; there can be only one auto column and it must be defined as a key, took 0.039 sec
[error]     at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
[error]     at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[error]     at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
[error]     at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:370)
[error]     at slick.jdbc.JdbcActionComponent$SchemaActionExtensionMethodsImpl$$anon$6.$anonfun$run$7(JdbcActionComponent.scala:292)
[error]     at slick.jdbc.JdbcActionComponent$SchemaActionExtensionMethodsImpl$$anon$6.$anonfun$run$7$adapted(JdbcActionComponent.scala:292)
[error]     at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement(JdbcBackend.scala:425)
[error]     at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement$(JdbcBackend.scala:420)
[error]     at slick.jdbc.JdbcBackend$BaseSession.withPreparedStatement(JdbcBackend.scala:489)
[error]     at slick.jdbc.JdbcActionComponent$SchemaActionExtensionMethodsImpl$$anon$6.$anonfun$run$6(JdbcActionComponent.scala:292)
[error]     at slick.jdbc.JdbcActionComponent$SchemaActionExtensionMethodsImpl$$anon$6.$anonfun$run$6$adapted(JdbcActionComponent.scala:292)
[error]     at scala.collection.immutable.Vector.foreach(Vector.scala:1856)
[error]     at slick.jdbc.JdbcActionComponent$SchemaActionExtensionMethodsImpl$$anon$6.run(JdbcActionComponent.scala:292)
[error]     at slick.jdbc.JdbcActionComponent$SchemaActionExtensionMethodsImpl$$anon$6.run(JdbcActionComponent.scala:290)
[error]     at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:28)
[error]     at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:25)
[error]     at slick.dbio.DBIOAction$$anon$4.$anonfun$run$3(DBIOAction.scala:239)
[error]     at scala.collection.immutable.Vector.foreach(Vector.scala:1856)
[error]     at slick.dbio.DBIOAction$$anon$4.run(DBIOAction.scala:239)
[error]     at slick.dbio.DBIOAction$$anon$4.run(DBIOAction.scala:237)
[error]     at slick.basic.BasicBackend$DatabaseDef$$anon$3.liftedTree1$1(BasicBackend.scala:276)
[error]     at slick.basic.BasicBackend$DatabaseDef$$anon$3.run(BasicBackend.scala:276)
[error]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]     at java.lang.Thread.run(Thread.java:829)
```

2021-06-30 09:55 UTC, mdibaiee commented
@nafg ah, so I think I need to make that column explicitly a key for this test to pass on MySQL. I will look at it 👍

2021-07-05 19:51 UTC, nafg approved these changes

2021-07-05 20:22 UTC, merged