Doc/generic jdbc connection
slick/slick pull request #2586
Opened 2022-10-19 22:18 UTC by ElectricWound

Guide to connect using any JDBC driver via a generic JdbcProfile implementation. The example uses a Databricks db.

2022-10-19 22:18 UTC, lightbend-cla-validator commented
Hi @ElectricWound,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

2022-10-20 16:46 UTC, ElectricWound commented
I signed the CLA

2022-10-20 19:06 UTC, nafg commented
Thanks!

2022-10-20 19:07 UTC, nafg requested changes

2022-10-20 19:07 UTC, nafg commented on doc/paradox/database.md
> +@@snip [GenericJdbcProfile.scala](../code/GenericJdbcProfile.scala) { #genericJdbcProfile }
CI shows that `paradoxMarkdownToHtml` is failing with:

```
[error] Label [genericJdbcProfile] not found in [/home/runner/work/slick/slick/doc/target/preprocessed/../code/GenericJdbcProfile.scala] at /home/runner/work/slick/slick/doc/target/preprocessed/database.md:72
[error] @@snip [GenericJdbcProfile.scala](../code/GenericJdbcProfile.scala) { #genericJdbcProfile }
[error] ^
```

2022-10-20 20:04 UTC, nafg approved these changes

2022-10-20 20:26 UTC, merged