[FRAM-4647] Enable adding arbitrary comments
slick/slick pull request #2595
Opened 2022-10-24 16:33 UTC by vaishnavirajiter

Add a new comment node on top of the query to enable adding comments as a part of the SQL statement

2022-10-24 18:41 UTC, nafg commented
@vaishnavirajiter Hi, this is an interesting idea. Why did you close it?

2022-10-25 17:04 UTC, vaishnavirajiter commented
Oh the PR is not ready for review yet. I also need to create the ticket and complete the contribution code of conduct related tasks.

2022-10-25 17:06 UTC, nafg commented
> Oh the PR is not ready for review yet.

It can be open and marked as a draft.

> I also need to create the ticket

I don't think a separate issue is necessary, any info can go in the PR.

> and complete the contribution code of conduct related tasks.

What do you mean by that?

2022-11-06 03:04 UTC, nafg requested changes
Thanks for the contribution! I left some questions.

2022-11-06 03:04 UTC, nafg commented on build.sbt
> +      version := "3.3.4-SNAPSHOT",
Why is this line here? It shouldn't be.

2022-11-06 03:04 UTC, nafg commented on slick/src/main/scala/slick/jdbc/JdbcActionComponent.scala
> +import slick.ast.{Comment, _}
This change seems unnecessary

2022-11-06 03:04 UTC, nafg commented on slick/src/main/scala/slick/compiler/QueryCompiler.scala
> +        childState.map(n => c.copy(child = n))
This line does nothing!

2022-11-06 03:04 UTC, nafg commented on slick/src/main/scala/slick/jdbc/JdbcActionComponent.scala
> +          (s"/* $comment */\n", child)
Since when is that valid comment syntax in SQL?

2022-11-06 03:04 UTC, nafg commented on slick/src/main/scala/slick/lifted/Query.scala
> +    new WrappingQuery[E, U, C](new Comment(comment, toNode), shaped)
`Comment` is a case class so `new` is unnecessary

2022-11-06 03:07 UTC, nafg commented on slick/src/main/scala/slick/jdbc/JdbcActionComponent.scala
> -import scala.language.{existentials, higherKinds}
This removal seems to be causing the build to fail

2022-11-06 03:08 UTC, nafg requested changes

2022-11-06 03:08 UTC, nafg commented on slick/src/main/scala/slick/jdbc/JdbcActionComponent.scala
> -import scala.util.control.NonFatal
This removal seems to be causing the build to fail

2022-11-30 00:47 UTC, nafg commented
@vaishnavirajiter would you like to have a call to go over the code?

2022-12-14 21:59 UTC, vaishnavirajiter commented
> @vaishnavirajiter would you like to have a call to go over the code?

Hello! Yes, a call would be great. Thanks! When would be a good time for you?

2022-12-14 23:47 UTC, nafg commented
@vaishnavirajiter now is fine. Are you on Discord?

2022-12-16 17:28 UTC, vaishnavirajiter commented
> @vaishnavirajiter now is fine. Are you on Discord?

No. We could set up something over Zoom, Does that work for you?

2022-12-18 02:38 UTC, nafg commented
> > @vaishnavirajiter now is fine. Are you on Discord?
> 
> No. We could set up something over Zoom, Does that work for you?

Zoom is good for the call, but how can we have a back and forth to figure out when to have the call, and to share the link privately?

2022-12-19 18:23 UTC, vaishnavirajiter commented
> > > @vaishnavirajiter now is fine. Are you on Discord?
> > 
> > 
> > No. We could set up something over Zoom, Does that work for you?
> 
> Zoom is good for the call, but how can we have a back and forth to figure out when to have the call, and to share the link privately?

Aah.. Okay. This is my Discord username - vaishnaviraj#8701

2023-01-12 11:48 UTC, jkugiya commented
Hi, @nafg @vaishnavirajiter 

The topic of commenting on SQL came up at my workplace and I was looking up implementations and found this PR.
Perhaps this PR only supports select statements, so I looked to see if I could create a new `DBIOAction` and found a method called `overrideStatements` in `SqlAction`. This one is likely to give us the results we are hoping for.

I may add new methods but may just add TIPS to the documentation.
What do you think?

https://github.com/jkugiya/slick/commit/6c89ffbf168eb838d525b98daaa22559f7e5cfbf

2023-01-12 12:02 UTC, jkugiya commented
> I may add new methods but may just add TIPS to the document.

- https://github.com/slick/slick/pull/810
- https://github.com/slick/slick/commit/706f2b1d3dc8adbceddf77a6ae4750264ff30dc3

Looking into the implementation history, `overrideStatements` is a hack against the query compiler and should probably not be listed as a TIPS...

2023-03-02 18:09 UTC, vaishnavirajiter commented
Closing this PR. Will create a new one when I work on this later.

2023-03-02 18:09 UTC, closed without merging