For some reason searching by dates in some timezones occasionally fails on Oracle 11g XE, avoid them in tests
slick/slick pull request #2685
Opened 2023-03-19 21:58 UTC by OlegYch

`testZonedDateTime` fails on searching date in "America/Argentina/Cordoba" around 5% of time on my machine, and around 60% of time for "Mexico/BajaSur" on github actions
no idea why...

2023-03-19 22:22 UTC, nafg commented
Maybe @smootoo or someone else from #1872 can explain

2023-03-19 22:33 UTC, nafg commented
In particular, what is meant exactly by the comment

> the database backends that support named timezones aren't necessarily configured for all  the zoneIds returned from ZoneId.getAvailableZoneIds (e.g. Oracle 11), so pick a subset to test with

What timezones is Oracle 11 configured for? How does one configure it?

I'd rather either get to the bottom of it and fix it and/or delete the bad ones entirely.

I guess one way of going about it would be to merge their deletion and have a new PR to add them back pending a solution :thinking: 

If only @hvesalai, @smootoo, or someone else could explain why those were chosen altogether.

Incidentally I just recently noticed that #1872 redefines `LocalTimeJdbcType` in `OracleProfile` (recently renamed `OracleLocalTimeJdbcType`) to along with a bunch of time types, but unlike the others doesn't redefine `localTimeType`. However I don't see how that could affect this test.

2023-03-20 10:44 UTC, smootoo commented
The test was originally written to use the JVM standard library call ZoneId.getAvailableZoneIds() to get ZoneIds to test with. The version of Oracle 11g that was being used at the time for the automated tests only worked with a limited subset of those ZoneIds. The hardcoded list of ZoneIds in the test was chosen as examples of the different styles of ZoneIds (e.g. "GB", "Etc/GMT+7", "Antarctica/Davis") and was supported in all the test environments.

I don't think it's possible to change the timezones that an Oracle version supports.

2023-03-21 05:20 UTC, nafg commented
@smootoo thanks, how did you obtain your list?

2023-03-21 18:31 UTC, smootoo commented
Chosen from what `java.time.ZoneId.getAvailableZoneIds()` returns

2023-03-21 18:33 UTC, nafg commented
> Chosen from what `java.time.ZoneId.getAvailableZoneIds()` returns

@smootoo yes but how did you know what zone IDs to eliminate? You didn't choose all of them.

2023-03-21 18:37 UTC, smootoo commented
If they failed in the tests, I didn't include them. After checking that the test failures were really because the Oracle instance didn't support them. By manually executing sql commands to check.

2023-04-17 08:20 UTC, nafg requested changes

2023-04-17 08:20 UTC, nafg commented on slick-testkit/src/main/scala/com/typesafe/slick/testkit/tests/JdbcTypeTest.scala
> +    //    "America/Argentina/Cordoba", // flaky on oracle
```suggestion
```

2023-04-17 08:20 UTC, nafg commented on slick-testkit/src/main/scala/com/typesafe/slick/testkit/tests/JdbcTypeTest.scala
> +    //    "Mexico/BajaSur", // flaky on oracle
```suggestion
```

2023-04-17 08:28 UTC, nafg approved these changes

2023-04-17 08:28 UTC, nafg commented
@mergifyio squash

2023-04-17 08:46 UTC, merged